config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }, except: %i[create update], path: '', path_names: { sign_in: 'login', sign_out: 'signed-out' }
  resources :posts
  resources :users do
    get 'profile'
  end
  resources :posts, only: %i[create update edit show destroy]
  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates_presence_of %i[first_name last_name nickname email]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_post, only: %i[show edit update destroy]
  # GET /posts or /posts.json
  def index
    @posts = Post.order('created_at DESC')
    @new_post = Post.new
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[attribute nickname last_name first_name])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[attribute nickname last_name first_name])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = User.find_by(id: params[:user_id]) or render status: :not_found

    @user_posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def owner?(resource)
    current_user == resource&.user
  end

  def owner(resource)
    resource&.user
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="p-4">
    <div class="navbar-text">
      <h1 class="d-flex h3 justify-content-center">Rails Test Blog</h1>
      <% if user_signed_in? %>
      <div class="d-flex justify-content-between">
        <p>Logged in as <strong><%= current_user.email %></strong>.</p>
        <div>
          <%= link_to 'My profile', user_profile_path(current_user.id), class:  'navbar-link' %> |
          <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link' %>
        </div>
      </div>
      <% else %>
        <div class="d-flex justify-content-center">
          <%= link_to "Sign up", new_user_registration_path, class: 'navbar-link' %> |
          <%= link_to "Login", new_user_session_path, class: 'navbar-link' %>
        </div>
      <% end %>
    </div>
    <% unless current_page?(root_path)%>
      <%= link_to "Go To Main", root_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post card">
  <div class="post__header card-header">
    <div class="post__info ">
      <p class="post__owner-link h5"><%= link_to owner(post).nickname, user_profile_path(post.user) %></p>
      <p class="post__date h5">Created <%= post.created_at %></p>
    </div>
    <div class="btn-group post__actions" role="group">
      <%= link_to 'Show', post, class: "post__show btn btn-outline-secondary btn-sm" %>
      <% if user_signed_in? %>
        <%= link_to 'Edit', edit_post_path(post), class: "post__edit btn btn btn-outline-secondary btn-sm" %>
        <%= link_to 'Destroy', post, method: :delete, class: "post__destroy btn btn btn-outline-danger btn-sm", data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </div>
  <div class="card-body blockquote"><%= post.content %></div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class: "btn btn-primary btn-lg" %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<section class="post-section">
  <% @posts.each do |post| %>
    <%= render "post", post: post %>
  <% end %>
</section>

<!-- Button trigger modal -->
<button type="button" class="btn btn-lg btn-primary new-post-btn" data-bs-toggle="modal" data-bs-target="#newPostModal">
  New Post
</button>

<!-- Modal -->
<div class="modal fade" id="newPostModal" tabindex="-1" aria-labelledby="newPostModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newPostModalLabel">New Post</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render 'form', post: @new_post %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<%= render "post", post: @post %>
<%= link_to 'Back', posts_path, class: "btn btn-primary btn-lg" %>

app/views/users/profile.html.erb
<div>
  <h1>Nickname <%= @user.nickname %></h1>
  <a href="mailto:<%= @user.email %>">Email</a>
  <h2>
    <% if @user == current_user %>
      You have <%= @user_posts.count %> posts.
    <% else %>
      Yuser have <%= @user_posts.count %> posts.
    <% end %>
  </h2>
</div>

<div>
  <% @user_posts.reverse.each do |post| %>
    <%= render "posts/post", post: post %>
  <% end %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>